version: '3'

services:
  nats:
    container_name: nats
    image: nats:latest
    command: >
      --user olo
      --pass password
      --cluster nats://0.0.0.0:6222
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    restart: always

  nats-replicator:
    container_name: nats-replicator
    image: nats-streaming:latest
    command: >
      --cluster_id nats-cluster
      --cluster_peers nats://nats:6222
      --store=FILE --dir=/data
      --max_msgs=1000000
      --max_bytes=1000000000
    volumes:
      - nats-data:/data
    restart: always

volumes:
  nats-data: